#!/bin/bash
set -e
set -x

if [[ -z "$ROOT" ]]; then
	echo 'Set $ROOT'
	exit 1
fi

SRC_DIR="$ROOT/usr/local/src"
mkdir -p $SRC_DIR

pushd "$SRC_DIR"

git clone https://github.com/andrey-utkin/gentoo.git gentoo.git
pushd gentoo.git
git remote add my https://github.com/andrey-utkin/gentoo.git
git fetch my
popd

git clone https://github.com/boto/botocore
git clone https://github.com/boto/boto3

popd
