#!/bin/bash
set -e
set -x

. /etc/profile
env-update

for python in /usr/bin/python?.?; do
	# As of botocore-1.4.7.ebuild, functional tests are not run with FEATURES="test"
	"$python" /usr/bin/nosetests -q /usr/local/src/botocore/tests/functional
	"$python" /usr/bin/nosetests -q /usr/local/src/botocore/tests/integration
	"$python" /usr/bin/nosetests -q /usr/local/src/boto3/tests/integration
done
